---
apiVersion: v2
appVersion: "0.2.9"
version: 1.0.0
name: installer
description: Quickly install pre-compiled binaries from Github releases.
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/installer"
icon: ""
type: application
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - installer
  - binary
  - binaries
  - compiled
sources:
  - https://github.com/jpillora/installer
  - https://hub.docker.com/r/nicholaswilde/installer
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.json
    - kind: changed
      description: Change tag to version-0.2.9 in order to reduce the number of chart updates
  artifacthub.io/images: |
    - name: installer
      image: ghcr.io/nicholaswilde/installer:version-0.2.9
