---
apiVersion: v2
appVersion: "0.1.1"
version: 1.0.0
name: twtxt
description: A Self-Hosted, Twitter™-like Decentralised microBlogging platform. No ads, no tracking, your content, your data!
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/twtxt"
icon: "https://twtxt.net/media/XsLsDHuisnXcL6NuUkYguK.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - twtxt
  - blogging
  - blog
  - social-network
sources:
  - https://github.com/prologic/twtxt
  - https://github.com/nicholaswilde/docker-twtxt
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Change tag to version-0.1.1 in order to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: twtxt
      image: ghcr.io/nicholaswilde/twtxt:version-0.1.1
