---
apiVersion: v2
appVersion: "154c581"
version: 1.0.0
name: golinks
description: A web app that allows you to create smart bookmarks, commands and aliases by pointing your web browser's default search engine at a running instance.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/golinks"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - search
  - browser
  - bookmarks
  - smart-bookmarks
  - golinks
sources:
  - https://github.com/prologic/golinks
  - https://github.com/nicholaswilde/docker-golinks
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.yaml
    - kind: changed
      description: Change tag to version-154c581 in order to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: golinks
      image: ghcr.io/nicholaswilde/golinks:version-154c581
