---
apiVersion: v2
appVersion: "900b76a"
version: 1.0.0
name: wiki
description: A self-hosted well uh wiki engine or content management system.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/wiki"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - wiki
  - web
  - blog
  - cms
  - app
sources:
  - https://github.com/prologic/wiki
  - https://github.com/nicholaswilde/docker-wiki
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.yaml
    - kind: changed
      description: Change tag to version-900b76a to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: wiki
      image: ghcr.io/nicholaswilde/wiki:version-900b76a
