---
apiVersion: v2
appVersion: "v0.1.0"
version: 1.0.0
name: shorturl
description: Self hosted web app for shortening urls (URL shortener)
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/shorturl"
icon: ""
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - url
  - shortener
  - shorten
  - shorturl
sources:
  - https://github.com/prologic/shorturl
  - https://github.com/nicholaswilde/docker-shorturl
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Simplify values.yaml
    - kind: changed
      description: Change tag to version-v0.1.0 to reduce the number of chart updates.
    - kind: removed
      description: secret from values.yaml
  artifacthub.io/images: |
    - name: shorturl
      image: ghcr.io/nicholaswilde/shorturl:version-v0.1.0
