---
apiVersion: v2
appVersion: 1.2.0
version: 1.0.0
name: novnc
description: The open source VNC client
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/novnc"
icon: "https://github.com/nicholaswilde/helm-charts/raw/main/images/novnc.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - novnc
  - vnc
  - remote
  - desktop
sources:
  - https://novnc.com/
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: values.schema.json
    - kind: changed
      description: Bump common to 0.1.13
    - kind: changed
      description: Change tag to version-1.2.0 to reduce the number of chart updates.
  artifacthub.io/images: |
    - name: novnc
      image: ghcr.io/nicholaswilde/novnc:version-1.2.0
