---
apiVersion: v2
appVersion: 1.8.0
version: 0.1.3
name: firefox-syncserver
description: This is an all-in-one package for running a self-hosted Firefox Sync server.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/firefox-syncserver"
icon: "https://upload.wikimedia.org/wikipedia/en/0/01/Firefox_Sync_logo.png"
dependencies:
  - name: common
    version: ~0.1.8
    repository: https://andre161292.github.io/nicholaswilde-helm-charts/
keywords:
  - server
  - sync
  - syncserver
  - firefox
sources:
  - https://moz-services-docs.readthedocs.io/en/latest/howtos/run-sync-1.5.html
  - https://hub.docker.com/r/crazymax/firefox-syncserver
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - Fixed linting issues.
    - Bumped common to ~0.1.8
    - Added icon
  artifacthub.io/images: |
    - name: firefox-syncserver
      image: ghcr.io/crazy-max/firefox-syncserver:1.8.0
